[package]
name = "subsecond-async-macros"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
syn = { workspace = true, features = ["full", "extra-traits"] }
quote.workspace = true

[dev-dependencies]
subsecond-async.workspace = true

[lib]
proc-macro = true
